name: yaru_test
description: Provides extensions for testing Yaru applications.
repository: https://github.com/ubuntu/yaru_test.dart
issue_tracker: https://github.com/ubuntu/yaru_test.dart/issues
version: 0.1.0-beta.3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  yaru: ^0.7.0
  yaru_widgets: ^2.4.1
  yaru_window_platform_interface: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4
